namespace P.E.A.K_MENU.Features.ItemSpawn;

/// <summary>
/// ItemSpawn 默认显示的物品以及默认排序。
///
/// 这里填写的是候选名称。
/// 游戏运行后会在实际物品数据库中进行匹配。
/// 当前版本不存在的物品会自动跳过。
/// </summary>
internal static class ItemSpawnDefaults
{
    internal static readonly string[] PreferredPrefabNames =
    {
        "ScoutEffigy",
        "Backpack",
        "BookOfBones",
        "Airplane Food",
        "HealingPuffShroom",
        "Bandages",
        "FirstAidKit",
        "Cure-All",
        "Antidote",
        "RescueHook",
        "RescueHook_Infinite",
        "ChainShooter",
        "RopeSpool",
        "Anti-Rope Spool",
        "RopeShooter",
        "RopeShooterAnti",
        "HealingDart Variant",
        "PortableStovetopItem",
        "ClimbingSpike",
        "MagicBean",
        "ShelfShroom",
        "CloudFungus",
        "BounceShroom",
        "WarpFungus",
        "Bugle",
        "Bugle_Magic",
        "Bugle_Scoutmaster Variant",
        "AncientIdol",
        "Torch",
        "Candle",
        "Lantern",
        "Lantern_Faerie",
        "Amulet_SuperJump",
        "Amulet_Healing",
        "Amulet_InfiniteStamina",
        "Amulet_Clone",
        "Cursed Skull",
        "RitualDagger",
        "Flag_Plantable_Checkpoint",
        "Flare",
        "Balloon",
        "BalloonBunch",
        "Marshmallow",
        "Glizzy",
        "Granola Bar",
        "Sports Drink",
        "Energy Drink",
        "Lollipop",
        "FortifiedMilk",
        "Item_Honeycomb",
        "Beehive",
        "PandorasBox",
        "MedicinalRoot",
        "Mandrake",
        "Prickleberry_Red",
        "Prickleberry_Gold",
        "Winterberry Orange",
        "Winterberry Yellow",
        "Pepper Berry",
        "Napberry",
        "Shroomberry_Red",
        "Shroomberry_Purple",
        "Shroomberry_Yellow",
        "Shroomberry_Blue",
        "Shroomberry_Green",
        "Snowball",
        "Heat Pack",
        "AloeVera",
        "Sunscreen",
        "Parasol",
        "CactusBall",
        "Dynamite",
        "Scorpion",
        "EarlyWorm",
        "Frog",
        "FrogLegs",
        "ScoutCannonItem",
        "Rocketpack",
        "AntiZooka",
        "Jetpack",
        "Glider",
        "ScoutsHonor",
        "TrailMix",
        "ScoutCookies",
        "ScoutCookies_Vanilla",
        "Item_Coconut_half",
        "Item_Coconut",
        "Apple Berry Red",
        "Apple Berry Yellow",
        "Apple Berry Green",
        "Berrynana Yellow",
        "Berrynana Brown",
        "Berrynana Blue",
        "Berrynana Pink",
        "Berrynana Peel Yellow",
        "Berrynana Peel Brown Variant",
        "Berrynana Peel Blue Variant",
        "Berrynana Peel Pink Variant",
        "Kingberry Green",
        "Kingberry Yellow",
        "Kingberry Purple",
        "Bugfix",
        "Mushroom Chubby",
        "Mushroom Cluster",
        "Mushroom Cluster Poison",
        "Mushroom Glow",
        "Mushroom Lace",
        "Mushroom Lace Poison",
        "Mushroom Normie",
        "Mushroom Normie Poison",
        "Clusterberry Black",
        "Clusterberry Red",
        "Clusterberry Yellow",
        "NestEgg",
        "NestEgg_Raven",
        "Egg",
        "EggRaven",
        "EggTurkey",
        "Shell Big",
        "Pirate Compass",
        "Parachute",
        "BingBong",
        "Frisbee",
        "Compass",
        "Binoculars",
        "Fannypack",
        "Passport",
    };

    /// <summary>
    /// 如果默认候选一个都没有匹配到，
    /// 则使用物品数据库排序后的前几个物品。
    /// </summary>
    internal const int FallbackItemCount = 12;
}
