namespace P.E.A.K_MENU.Features.ItemSpawn;

/// <summary>
/// ItemSpawn 默认显示的物品以及默认排序。
///
/// 这里填写的是候选名称。
/// 游戏运行后会在实际物品数据库中进行匹配。
/// 当前版本不存在的物品会自动跳过。
/// </summary>
internal static class ItemSpawnDefaults
{
    internal static readonly string[] PreferredPrefabNames =
    {
        "ScoutEffigy",
        "Backpack",
        "BookOfBones",
        "Airplane Food",
        "Cure-All",
        "RopeSpool",
        "Anti-Rope Spool",
        "RopeShooter",
        "RopeShooterAnti",
        "RescueHook",
        "RescueHook_Infinite",
        "PortableStovetopItem",
        "HealingDart Variant",
        "AloeVera",
        "Amulet_Clone",
        "Amulet_Healing",
        "Amulet_InfiniteStamina",
        "Amulet_SuperJump",
        "AncientIdol",
        "Antidote",
        "AntiZooka",
        "Apple Berry Green",
        "Apple Berry Red",
        "Apple Berry Yellow",
        "Balloon",
        "BalloonBunch",
        "Bandages",
        "Basketball",
        "Beehive",
        "Berrynana Blue",
        "Berrynana Brown",
        "Berrynana Peel Blue Variant",
        "Berrynana Peel Brown Variant",
        "Berrynana Peel Pink Variant",
        "Berrynana Peel Yellow",
        "Berrynana Pink",
        "Berrynana Yellow",
        "BingBong",
        "Binoculars",
        "BounceShroom",
        "Bugfix",
        "Bugle",
        "Bugle_Magic",
        "Bugle_Scoutmaster Variant",
        "CactusBall",
        "Candle",
        "ChainShooter",
        "ClimbingSpike",
        "CloudFungus",
        "Clusterberry Black",
        "Clusterberry Red",
        "Clusterberry Yellow",
        "Clusterberry_UNUSED",
        "Compass",
        "Cursed Skull",
        "Dynamite",
        "EarlyWorm",
        "Egg",
        "EggRaven",
        "EggTurkey",
        "Energy Drink",
        "Fannypack",
        "FirstAidKit",
        "Flag_Plantable_Checkpoint",
        "Flare",
        "FortifiedMilk",
        "Frisbee",
        "Frog",
        "FrogLegs",
        "Glider",
        "Glizzy",
        "Granola Bar",
        "HealingPuffShroom",
        "Heat Pack",
        "Item_Coconut",
        "Item_Coconut_half",
        "Item_Honeycomb",
        "Jetpack",
        "Kingberry Green",
        "Kingberry Purple",
        "Kingberry Yellow",
        "Lantern",
        "Lantern_Faerie",
        "Lollipop",
        "MagicBean",
        "Mandrake",
        "Marshmallow",
        "MedicinalRoot",
        "Mushroom Chubby",
        "Mushroom Cluster",
        "Mushroom Cluster Poison",
        "Mushroom Glow",
        "Mushroom Lace",
        "Mushroom Lace Poison",
        "Mushroom Normie",
        "Mushroom Normie Poison",
        "Napberry",
        "NestEgg",
        "NestEgg_Raven",
        "PandorasBox",
        "Parachute",
        "Parasol",
        "Pepper Berry",
        "Pirate Compass",
        "Prickleberry_Gold",
        "Prickleberry_Red",
        "Scorpion",
        "ScoutCannonItem",
        "ScoutCookies",
        "ScoutCookies_Vanilla",
        "Rocketpack",
        "RitualDagger",
        "ScoutsHonor",
        "ShelfShroom",
        "Shell Big",
        "Shroomberry_Blue",
        "Shroomberry_Green",
        "Shroomberry_Purple",
        "Shroomberry_Red",
        "Shroomberry_Yellow",
        "Skull",
        "Snowball",
        "Sports Drink",
        "Sunscreen",
        "Torch",
        "TrailMix",
        "WarpFungus",
        "Winterberry Orange",
        "Winterberry Yellow",
    };

    /// <summary>
    /// 如果默认候选一个都没有匹配到，
    /// 则使用物品数据库排序后的前几个物品。
    /// </summary>
    internal const int FallbackItemCount = 12;
}
