<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>

    <AssemblyName>ruangfafa.peakmenu</AssemblyName>
    <AssemblyTitle>P.E.A.K_MENU</AssemblyTitle>

    <Version>0.3.4</Version>

    <Description>PEAK 游戏内实用菜单，包含物品生成、玩家传送、飞行、状态控制、主题与可调整界面。</Description>
  </PropertyGroup>

  <PropertyGroup>
    <IsThunderstorePackable>true</IsThunderstorePackable>

    <ThunderstoreName>PEAK_MENU_CN</ThunderstoreName>

    <ThunderstoreDescription>PEAK 游戏内实用菜单，包含物品生成、玩家传送、坐标飞行、状态控制、主题与可调整界面。</ThunderstoreDescription>

    <ThunderstoreCommunities>peak</ThunderstoreCommunities>

    <ThunderstoreCategories>mods</ThunderstoreCategories>
  </PropertyGroup>

  <ItemGroup>
    <ModFile
      Include="$(TargetPath)"
      Destination="plugins/" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Icons\*.png" />
  </ItemGroup>

  <ItemGroup>
    <ThunderstorePackageFile Include="$(SolutionRoot)README.md" />
    <ThunderstorePackageFile Include="$(SolutionRoot)CHANGELOG.md" />
    <ThunderstorePackageFile Include="$(SolutionRoot)icon.png" />
    <ThunderstorePackageFile Include="$(SolutionRoot)LICENSE" />

    <ThunderstoreDependency
      Include="BepInEx-BepInExPack_PEAK"
      Version="5.4.75301" />

    <ThunderstoreDependency
      Include="Hamunii-AutoHookGenPatcher"
      Version="1.0.7" />

    <ThunderstoreDependency
      Include="Hamunii-DetourContext_Dispose_Fix"
      Version="1.0.5" />
  </ItemGroup>

</Project>
